spring:
  application:
    name: ecomOauth
    
#Google    
security:
  oauth2:
    client:
      clientId: 136761395151-cdut8t3b5fgbcqsm31fr002i22j073ja.apps.googleusercontent.com
      clientSecret: 5CFWOsehMQfonUNqo1pc9Tnu
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false
   
#Facebook  
#security:
  #oauth2:
   # client:
     # clientId: 396667311717996
     # clientSecret: dcc989494c8f6687275b1c57f335d8d1
     # accessTokenUri: https://graph.facebook.com/oauth/access_token
     # userAuthorizationUri: https://www.facebook.com/dialog/oauth
     # tokenName: oauth_token
     # authenticationScheme: query
     # clientAuthenticationScheme: form
    #resource:
    #  userInfoUri: https://graph.facebook.com/me?fields=email,name,id   
    

   
      
logging:
  level:
    org.springframework.security: DEBUG